"""add isbn to books

Revision ID: 2e99cf0115f9
Revises: 83a0ab39337b
Create Date: 2026-08-18 10:12:03.212186

"""
from typing import Sequence, Union
import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e99cf0115f9'
down_revision: Union[str, Sequence[str], None] = '83a0ab39337b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_books_isbn', ['isbn'])


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('uq_books_isbn', type_='unique')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
