"""add unique constraint and seed data

Revision ID: 98b478c39e96
Revises: 2e99cf0115f9
Create Date: 2026-08-18 10:24:38.900653

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b478c39e96'
down_revision: Union[str, Sequence[str], None] = '2e99cf0115f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_books_isbn', ['isbn'])

    authors_table = sa.table(
        'authors',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String)
    )
    books_table = sa.table(
        'books',
        sa.column('id', sa.Integer),
        sa.column('title', sa.String),
        sa.column('author_id', sa.Integer),
        sa.column('price', sa.Float),
        sa.column('genres', sa.JSON),
        sa.column('category', sa.String),  # Enums are stored as text/strings in SQLite
        sa.column('is_available', sa.Boolean),
        sa.column('pages', sa.Integer),
        sa.column('isbn', sa.String),
        sa.column('created_at', sa.DateTime),
        sa.column('description', sa.Text)
    )

    op.bulk_insert(authors_table,
                   [{
                       "id":1,
                       "name": "Richard Gleeson"
                   }])
    op.bulk_insert(books_table, [
        {
            "id": 1,
            "title": "The Great Gatsby",
            "author_id": 1,
            "price": 14.99,
            "genres": '["Fiction", "Classic"]',
            "category": "other",
            "is_available": True,
            "pages": 180,
            "isbn": "9780743273565",
            "created_at": datetime.utcnow(),
            "description": "A story about the jazz age."
        },
        {
            "id": 2,
            "title": "A Brief History of Time",
            "author_id": 1,
            "price": 19.99,
            "genres": '["Science", "Non-Fiction"]',
            "category": "other",
            "is_available": True,
            "pages": 256,
            "isbn": "9780553380163",
            "created_at": datetime.utcnow(),
            "description": "A book about cosmology."
        }
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
