"""update ISBN to db

Revision ID: fd1d63ef3964
Revises: 98b478c39e96
Create Date: 2026-08-18 10:32:45.735253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1d63ef3964'
down_revision: Union[str, Sequence[str], None] = '98b478c39e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ISBN', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_books_isbn'), type_='unique')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_books_isbn'), ['isbn'])
        batch_op.drop_column('ISBN')

    # ### end Alembic commands ###
