import type { Meta, StoryObj } from '@storybook/react-vite';
import { Checkbox } from './Checkbox';
import { expect, fn, userEvent, within } from '@storybook/test';

const meta: Meta<typeof Checkbox> = {
  title: 'Components/Checkbox',
  component: Checkbox,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  
  argTypes: {
    checked: {
      control: 'boolean',
      description: 'The checked state of the checkbox input element',
    },
    disabled: {
      control: 'boolean',
      description: 'Disables the input and prevents user toggling actions',
    },
    label: {
      control: 'text',
      description: 'The descriptive text accompanying the checkbox input element',
    },
  },
  // Automatically captures state change triggers in the Actions log window
  args: { 
    label: 'Accept Terms & Conditions', 
    disabled: false,
    onChange: fn(),
  },
} satisfies Meta<typeof Checkbox>;

export default meta;
type Story = StoryObj<typeof Checkbox>;

/**
 * 1. Default Interactive Playground
 * Simulates a full toggle sequence, ensuring the underlying state updates correctly.
 */
export const Default: Story = {
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    
    // Target the checkbox using its accessible name generated by the label text
    const checkbox = canvas.getByRole('checkbox', { name: /accept terms & conditions/i });

    // Ensure it starts in an unchecked state
    await expect(checkbox).not.toBeChecked();

    // Trigger a simulated user click interaction
    await userEvent.click(checkbox);

    // Verify the change handler was successfully called
    await expect(args.onChange).toHaveBeenCalled();
  },
};

/**
 * 2. Pre-Checked State
 * Verifies the component functions normally when initialized as checked.
 */
export const Checked: Story = {
  args: {
    checked: true,
    label: 'Subscribe to newsletter',
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    const checkbox = canvas.getByRole('checkbox', { name: /subscribe to newsletter/i });

    // Verify initial true state
    await expect(checkbox).toBeChecked();

    // Click to uncheck
    await userEvent.click(checkbox);
    await expect(args.onChange).toHaveBeenCalled();
  },
};

/**
 * 3. Disabled State Test
 * Validates that an inactive checkbox completely ignores click actions.
 */
export const Disabled: Story = {
  args: {
    disabled: true,
    label: 'Locked Choice',
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    const checkbox = canvas.getByRole('checkbox', { name: /locked choice/i });

    // Assert standard HTML element disabled states
    await expect(checkbox).toBeDisabled();

    // Click checking mechanism with safety parameters bypassed to capture native blocking
    await userEvent.click(checkbox, { pointerEventsCheck: 0 });
    
    // Assert click was discarded by the element layer
    await expect(args.onChange).not.toHaveBeenCalled();
  },
};